name: Check Kubernetes documentation links

on:
  push:
  schedule:
    - cron: '0 0 */15 * *'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
